# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Debug VPN slow connection

env:
  PYTHONUNBUFFERED: "1"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get --assume-yes --no-install-recommends install openvpn          
          openvpn --version
          sudo python -m pip install --upgrade pip
          sudo pip install -r requirements/requirements.txt
          sudo pip install -r requirements/requirements-dev.txt
          playwright install chromium
      - name: Run
        env:
          VPN_USERNAME: ${{ secrets.VPN_USERNAME }}
          VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
        run: |
          sudo -E python app_vpn_debug.py
