name: Scan products (get IDs) second half

env:
  PYTHONUNBUFFERED: "1"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get --assume-yes --no-install-recommends install openvpn
          openvpn --version
      - name: Install Python dependencies
        run: |
          python3 -m pip install --user --upgrade pip
          sudo python3 -m pip install --break-system-packages -r requirements/requirements.txt --ignore-installed
          sudo python3 -m pip install --break-system-packages -r requirements/requirements-dev.txt --ignore-installed
      - name: Install Playwright
        run: sudo playwright install chromium
      - name: Mypy
        run: |
          sudo python3 -m mypy src/
      - name: Pylint
        run: |
          sudo python3 -m pylint src/
      - name: Run
        env:
          DATABASE_NEON_URL: ${{ secrets.DATABASE_NEON_URL }}
          URL_SEED: ${{ secrets.URL_SEED }}
          VPN_USERNAME: ${{ secrets.VPN_USERNAME }}
          VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
          API_URL_TEMPLATE: ${{ vars.API_URL_TEMPLATE }}
          CF_URL: ${{ vars.CF_URL }}
        run: |
          sudo -E python3 app.py --operation scan --partial second_half
      - name: Handle failure
        if: ${{ failure() }}
        env:
          URL_WEBHOOK_MAKE: ${{ secrets.URL_WEBHOOK_MAKE }}
        run: |
          echo "Run step failed. Handling failure..."
          # Launch the scan_failover workflow (delayed)
          curl $URL_WEBHOOK_MAKE -H "Content-Type: application/json" -d '{"operation": "scan", "partial": "second_half"}'
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snapshots
          path: |
            ./scanned_prodcts.pkl
            logger_msgs.log
