name: Triggered Workflow

on:
  workflow_dispatch:
    inputs:
      trigger_message:
        description: "Message from the API"
        required: true
        default: "No message provided"

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a script
        run: echo "The workflow was triggered by Zapier!"
