name: Store products (get full info) first half

env:
  PYTHONUNBUFFERED: "1"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Update package lists
        run: sudo apt-get update

      - name: Install OpenVPN
        run: |
          sudo apt-get --assume-yes --no-install-recommends install openvpn
          openvpn --version

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install production dependencies
        run: pip install -r requirements/requirements.txt

      - name: Install development dependencies
        run: pip install -r requirements/requirements-dev.txt

      - name: Install Playwright browser
        run: playwright install chromium

      - name: Mypy
        run: |
          PYTHON_PATH=$(which python)
          sudo -E "$PYTHON_PATH" -m mypy src/

      - name: Pylint
        run: |
          PYTHON_PATH=$(which python)
          sudo -E "$PYTHON_PATH" -m pylint src/

      - name: Run
        uses: nick-fields/retry@v3
        env:
          DATABASE_NEON_URL: ${{ secrets.DATABASE_NEON_URL }}
          URL_SEED: ${{ secrets.URL_SEED }}
          VPN_USERNAME: ${{ secrets.VPN_USERNAME }}
          VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
          API_URL_TEMPLATE: ${{ vars.API_URL_TEMPLATE }}
          CF_URL: ${{ vars.CF_URL }}
        with:
          timeout_minutes: 360
          max_attempts: 2
          retry_on: error
          command: sudo -E $(which python) app.py --operation store --partial first_half

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snapshots
          path: |
            ./*.png
            logger_msgs.log
