name: Triggered Workflow

on:
  repository_dispatch:
    types: [trigger]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a script
        run: echo "The workflow was triggered by Zapier!"
